export const courses = [
    {
        id: 1,
        title: "Mathematics",
        image: "/images/math.jpg",
        level: "Grade 1–12",
        students: "3,200+",
        rating: 4.9,
        price: "₹999/month",
        popular: true,
        link: "/mathematics",
    },
    {
        id: 2,
        title: "Coding",
        image: "/images/coding.jpg",
        level: "Beginner to Advanced",
        students: "2,100+",
        rating: 4.8,
        price: "₹1,499/month",
        popular: false,
        link: "/explore-coding-courses",
    },
    {
        id: 3,
        title: "English Speaking",
        image: "/images/english.jpg",
        level: "All Ages",
        students: "1,500+",
        rating: 4.9,
        price: "₹899/month",
        popular: true,
        link: "/english-speaking",
    },

    {
        id: 3,
        title: "English Speaking",
        image: "/images/english.jpg",
        level: "All Ages",
        students: "1,500+",
        rating: 4.9,
        price: "₹899/month",
        popular: true,
        link: "/english-speaking",
    },
];